from pydantic import BaseModel
from pydantic import Field

class LabelValue(BaseModel):
    report_date: list = Field([''], const=True)
    updated_on: list = Field([''], const=True)
    income_tax: list = Field(['tax'], const=True)
    resident_tax: list = Field(['tax'], const=True)
    life_insurance: list = Field(['insurance'], const=True)
    employment_insurance: list = Field(['insurance'], const=True)
    health_insurance: list = Field(['insurance'], const=True)
    nursing_insurance: list = Field(['insurance'], const=True)
    welfare_pension: list = Field(['insurance'], const=True)
    savings: list = Field(['asset'], const=True)
    securities: list = Field(['asset'], const=True)
    n401k: list = Field(['asset'], const=True)
    rent: list = Field(['cashout'], const=True)
    electricity: list = Field(['cashout','lifeline'], const=True)
    gas: list = Field(['cashout','lifeline'], const=True)
    water: list = Field(['cashout','lifeline'], const=True)
    newspaper: list = Field(['cashout',], const=True)
    cable_tv: list = Field(['cashout',], const=True)
    tennis_club: list = Field(['cashout',], const=True)
    pilates: list = Field(['cashout',], const=True)
    nhk: list = Field(['cashout',], const=True)
    parking: list = Field(['cashout',], const=True)
    car: list = Field(['cashout',], const=True)
    creditcard_visa: list = Field(['cashout','creditcard'], const=True)
    creditcard_view: list = Field(['cashout','creditcard'], const=True)
    creditcard_mc: list = Field(['cashout','creditccard'], const=True)
    basic_life: list = Field(['cashout',], const=True)
    remote_work: list = Field(['cashout',], const=True)