version: "3.3"

services:
  jupyter:
    image: jupyter/scipy-notebook:33add21fab64
    restart: "always"
    volumes:
      - /home/jovyan
    ports:
      - "8888:8888"
  db:
    image: postgres:13.1-alpine
    restart: "no"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - service00
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: "no"

  # elasticsearch
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - service00
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    restart: "always"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - service00
    ports:
     - "5601:5601"
    restart: "always"

  mongo:
    image: mongo:5.0.6-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"

volumes:
  data01:
    driver: local
  db-data:
    driver: local

networks:
  service00:
