version: "3.3"

services:
  db:
    image: postgres:13.1-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - service00
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  # elasticsearch
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    environment:
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - service00
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - service00
    ports:
     - "5601:5601"
    restart: always

volumes:
  data01:
    driver: local
  db-data:
    driver: local

networks:
  service00:
