version: "3.3"

services:
  jupyter:
    image: jupyter/all-spark-notebook:x86_64-python-3.11d
    networks:
      - service00
  postgres:
    image: postgres:16.2-alpine
    networks:
      - service00
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  mariadb:
    image: mariadb:11.3-jammy
    networks:
      - service00
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  mysql:
    image: mysql:8.0-bookworm
    networks:
      - service00
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3307"

  # elasticsearch
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    environment:
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    networks:
      - service00
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    restart: "always"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.8
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - service00
    ports:
     - "5601:5601"
    restart: "always"

  mongo:
    image: mongo:5.0.6-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - service00

volumes:
  data01:
    driver: local
  mongo-data:
    driver: local
  jupyter-data:
    driver: local

networks:
  service00:
